var wasmImports = {
    n: (...args) => ___cxa_begin_catch(...args),
    z: (...args) => ___cxa_end_catch(...args),
    a: (...args) => ___cxa_find_matching_catch_2(...args),
    f: (...args) => ___cxa_find_matching_catch_3(...args),
    gc: (...args) => ___cxa_rethrow(...args),
    h: (...args) => ___cxa_throw(...args),
    fc: (...args) => ___cxa_uncaught_exceptions(...args),
    c: (...args) => ___resumeException(...args),
    vk: (...args) => ___syscall__newselect(...args),
    uk: (...args) => ___syscall_chdir(...args),
    tk: (...args) => ___syscall_faccessat(...args),
    H: (...args) => ___syscall_fcntl64(...args),
    sk: (...args) => ___syscall_getcwd(...args),
    rk: (...args) => ___syscall_getdents64(...args),
    qk: (...args) => ___syscall_ioctl(...args),
    pk: (...args) => ___syscall_lstat64(...args),
    ok: (...args) => ___syscall_mkdirat(...args),
    nk: (...args) => ___syscall_newfstatat(...args),
    ec: (...args) => ___syscall_openat(...args),
    mk: (...args) => ___syscall_readlinkat(...args),
    lk: (...args) => ___syscall_stat64(...args),
    kk: (...args) => ___syscall_unlinkat(...args),
    fk: (...args) => __abort_js(...args),
    ek: (...args) => __gmtime_js(...args),
    dk: (...args) => __localtime_js(...args),
    ck: (...args) => __mktime_js(...args),
    bk: (...args) => __tzset_js(...args),
    ak: (...args) => _alBuffer3f(...args),
    $j: (...args) => _alBuffer3i(...args),
    ia: (...args) => _alBufferData(...args),
    _j: (...args) => _alBufferf(...args),
    Zj: (...args) => _alBufferfv(...args),
    Yj: (...args) => _alBufferi(...args),
    bc: (...args) => _alBufferiv(...args),
    ha: (...args) => _alDeleteBuffers(...args),
    Ia: (...args) => _alDeleteSources(...args),
    Xj: (...args) => _alDisable(...args),
    ac: (...args) => _alDistanceModel(...args),
    Wj: (...args) => _alDopplerFactor(...args),
    Vj: (...args) => _alDopplerVelocity(...args),
    Uj: (...args) => _alEnable(...args),
    ga: (...args) => _alGenBuffers(...args),
    Ha: (...args) => _alGenSources(...args),
    Tj: (...args) => _alGetBoolean(...args),
    Sj: (...args) => _alGetBooleanv(...args),
    Rj: (...args) => _alGetBuffer3f(...args),
    Qj: (...args) => _alGetBuffer3i(...args),
    Pj: (...args) => _alGetBufferf(...args),
    Oj: (...args) => _alGetBufferfv(...args),
    Nj: (...args) => _alGetBufferi(...args),
    Mj: (...args) => _alGetBufferiv(...args),
    Lj: (...args) => _alGetDouble(...args),
    Kj: (...args) => _alGetDoublev(...args),
    $b: (...args) => _alGetEnumValue(...args),
    Jj: (...args) => _alGetError(...args),
    Ij: (...args) => _alGetFloat(...args),
    Hj: (...args) => _alGetFloatv(...args),
    Gj: (...args) => _alGetInteger(...args),
    Fj: (...args) => _alGetIntegerv(...args),
    Hc: (...args) => _glStencilFunc(...args),
    Ej: (...args) => _alGetListener3f(...args),
    Dj: (...args) => _alGetListener3i(...args),
    Cj: (...args) => _alGetListenerf(...args),
    Bj: (...args) => _alGetListenerfv(...args),
    Aj: (...args) => _alGetListeneri(...args),
    zj: (...args) => _alGetListeneriv(...args),
    yj: (...args) => _alGetSource3f(...args),
    xj: (...args) => _alGetSource3i(...args),
    _b: (...args) => _alGetSourcef(...args),
    wj: (...args) => _alGetSourcefv(...args),
    u: (...args) => _alGetSourcei(...args),
    vj: (...args) => _alGetSourceiv(...args),
    Zb: (...args) => _alGetString(...args),
    Ga: (...args) => _alIsBuffer(...args),
    uj: (...args) => _alIsEnabled(...args),
    tj: (...args) => _alIsExtensionPresent(...args),
    sj: (...args) => _alIsSource(...args),
    Fa: (...args) => _alListener3f(...args),
    rj: (...args) => _alListener3i(...args),
    Yb: (...args) => _alListenerf(...args),
    Xb: (...args) => _alListenerfv(...args),
    qj: (...args) => _alListeneri(...args),
    pj: (...args) => _alListeneriv(...args),
    D: (...args) => _alSource3f(...args),
    ra: (...args) => _alSource3i(...args),
    Ea: (...args) => _alSourcePause(...args),
    oj: (...args) => _alSourcePausev(...args),
    R: (...args) => _alSourcePlay(...args),
    nj: (...args) => _alSourcePlayv(...args),
    G: (...args) => _alSourceQueueBuffers(...args),
    mj: (...args) => _alSourceRewind(...args),
    lj: (...args) => _alSourceRewindv(...args),
    $: (...args) => _alSourceStop(...args),
    kj: (...args) => _alSourceStopv(...args),
    fa: (...args) => _alSourceUnqueueBuffers(...args),
    v: (...args) => _alSourcef(...args),
    jj: (...args) => _alSourcefv(...args),
    y: (...args) => _alSourcei(...args),
    ij: (...args) => _alSourceiv(...args),
    hj: (...args) => _alSpeedOfSound(...args),
    Wb: (...args) => _alcCloseDevice(...args),
    Vb: (...args) => _alcCreateContext(...args),
    Ub: (...args) => _alcDestroyContext(...args),
    gj: (...args) => _alcGetIntegerv(...args),
    qa: (...args) => _alcIsExtensionPresent(...args),
    Da: (...args) => _alcMakeContextCurrent(...args),
    Tb: (...args) => _alcOpenDevice(...args),
    fj: (...args) => _alcSuspendContext(...args),
    jk: (...args) => _clock_time_get(...args),
    ej: (...args) => _eglBindAPI(...args),
    Sb: (...args) => _eglChooseConfig(...args),
    Rb: (...args) => _eglCreateContext(...args),
    Qb: (...args) => _eglCreateWindowSurface(...args),
    dj: (...args) => _eglDestroyContext(...args),
    cj: (...args) => _eglDestroySurface(...args),
    bj: (...args) => _eglGetConfigAttrib(...args),
    Ca: (...args) => _eglGetDisplay(...args),
    aj: (...args) => _eglGetError(...args),
    Pb: (...args) => _eglInitialize(...args),
    Ob: (...args) => _eglMakeCurrent(...args),
    $i: (...args) => _eglQueryString(...args),
    Nb: (...args) => _eglSwapBuffers(...args),
    _i: (...args) => _eglSwapInterval(...args),
    Zi: (...args) => _eglTerminate(...args),
    Yi: (...args) => _eglWaitGL(...args),
    Xi: (...args) => _eglWaitNative(...args),
    q: (...args) => _emscripten_asm_const_int(...args),
    B: (...args) => _emscripten_asm_const_int_sync_on_main_thread(...args),
    Wi: (...args) => _emscripten_asm_const_ptr_sync_on_main_thread(...args),
    Mb: (...args) => _emscripten_date_now(...args),
    Lb: (...args) => _emscripten_err(...args),
    Vi: (...args) => _emscripten_exit_fullscreen(...args),
    Ui: (...args) => _emscripten_exit_pointerlock(...args),
    Ti: (...args) => _emscripten_fetch_free(...args),
    ea: (...args) => _emscripten_get_device_pixel_ratio(...args),
    U: (...args) => _emscripten_get_element_css_size(...args),
    Kb: (...args) => _emscripten_get_gamepad_status(...args),
    Jb: (...args) => _emscripten_get_now(...args),
    Si: (...args) => _emscripten_get_num_gamepads(...args),
    Ri: (...args) => _emscripten_get_screen_size(...args),
    Qi: (...args) => _emscripten_glActiveTexture(...args),
    Pi: (...args) => _emscripten_glAttachShader(...args),
    Oi: (...args) => _emscripten_glBeginQuery(...args),
    Ni: (...args) => _emscripten_glBeginQueryEXT(...args),
    Mi: (...args) => _emscripten_glBeginTransformFeedback(...args),
    Li: (...args) => _emscripten_glBindAttribLocation(...args),
    Ki: (...args) => _emscripten_glBindBuffer(...args),
    Ji: (...args) => _emscripten_glBindBufferBase(...args),
    Ii: (...args) => _emscripten_glBindBufferRange(...args),
    Hi: (...args) => _emscripten_glBindFramebuffer(...args),
    Gi: (...args) => _emscripten_glBindRenderbuffer(...args),
    Fi: (...args) => _emscripten_glBindSampler(...args),
    Ei: (...args) => _emscripten_glBindTexture(...args),
    Di: (...args) => _emscripten_glBindTransformFeedback(...args),
    Ci: (...args) => _emscripten_glBindVertexArray(...args),
    Bi: (...args) => _emscripten_glBindVertexArrayOES(...args),
    Ai: (...args) => _emscripten_glBlendColor(...args),
    zi: (...args) => _emscripten_glBlendEquation(...args),
    yi: (...args) => _emscripten_glBlendEquationSeparate(...args),
    xi: (...args) => _emscripten_glBlendFunc(...args),
    wi: (...args) => _emscripten_glBlendFuncSeparate(...args),
    vi: (...args) => _emscripten_glBlitFramebuffer(...args),
    ui: (...args) => _emscripten_glBufferData(...args),
    ti: (...args) => _emscripten_glBufferSubData(...args),
    si: (...args) => _emscripten_glCheckFramebufferStatus(...args),
    ri: (...args) => _emscripten_glClear(...args),
    qi: (...args) => _emscripten_glClearBufferfi(...args),
    pi: (...args) => _emscripten_glClearBufferfv(...args),
    oi: (...args) => _emscripten_glClearBufferiv(...args),
    ni: (...args) => _emscripten_glClearBufferuiv(...args),
    mi: (...args) => _emscripten_glClearColor(...args),
    li: (...args) => _emscripten_glClearDepthf(...args),
    ki: (...args) => _emscripten_glClearStencil(...args),
    ji: (...args) => _emscripten_glClientWaitSync(...args),
    ii: (...args) => _emscripten_glClipControlEXT(...args),
    hi: (...args) => _emscripten_glColorMask(...args),
    gi: (...args) => _emscripten_glCompileShader(...args),
    fi: (...args) => _emscripten_glCompressedTexImage2D(...args),
    ei: (...args) => _emscripten_glCompressedTexImage3D(...args),
    di: (...args) => _emscripten_glCompressedTexSubImage2D(...args),
    ci: (...args) => _emscripten_glCompressedTexSubImage3D(...args),
    bi: (...args) => _emscripten_glCopyBufferSubData(...args),
    ai: (...args) => _emscripten_glCopyTexImage2D(...args),
    $h: (...args) => _emscripten_glCopyTexSubImage2D(...args),
    _h: (...args) => _emscripten_glCopyTexSubImage3D(...args),
    Zh: (...args) => _emscripten_glCreateProgram(...args),
    Yh: (...args) => _emscripten_glCreateShader(...args),
    Xh: (...args) => _emscripten_glCullFace(...args),
    Wh: (...args) => _emscripten_glDeleteBuffers(...args),
    Vh: (...args) => _emscripten_glDeleteFramebuffers(...args),
    Uh: (...args) => _emscripten_glDeleteProgram(...args),
    Th: (...args) => _emscripten_glDeleteQueries(...args),
    Sh: (...args) => _emscripten_glDeleteQueriesEXT(...args),
    Rh: (...args) => _emscripten_glDeleteRenderbuffers(...args),
    Qh: (...args) => _emscripten_glDeleteSamplers(...args),
    Ph: (...args) => _emscripten_glDeleteShader(...args),
    Oh: (...args) => _emscripten_glDeleteSync(...args),
    Nh: (...args) => _emscripten_glDeleteTextures(...args),
    Mh: (...args) => _emscripten_glDeleteTransformFeedbacks(...args),
    Lh: (...args) => _emscripten_glDeleteVertexArrays(...args),
    Kh: (...args) => _emscripten_glDeleteVertexArraysOES(...args),
    Jh: (...args) => _emscripten_glDepthFunc(...args),
    Ih: (...args) => _emscripten_glDepthMask(...args),
    Hh: (...args) => _emscripten_glDepthRangef(...args),
    Gh: (...args) => _emscripten_glDetachShader(...args),
    Fh: (...args) => _emscripten_glDisable(...args),
    Eh: (...args) => _emscripten_glDisableVertexAttribArray(...args),
    Dh: (...args) => _emscripten_glDrawArrays(...args),
    Ch: (...args) => _emscripten_glDrawArraysInstanced(...args),
    Bh: (...args) => _emscripten_glDrawArraysInstancedANGLE(...args),
    Ah: (...args) => _emscripten_glDrawArraysInstancedARB(...args),
    zh: (...args) => _emscripten_glDrawArraysInstancedEXT(...args),
    yh: (...args) => _emscripten_glDrawArraysInstancedNV(...args),
    xh: (...args) => _emscripten_glDrawBuffers(...args),
    wh: (...args) => _emscripten_glDrawBuffersEXT(...args),
    vh: (...args) => _emscripten_glDrawBuffersWEBGL(...args),
    uh: (...args) => _emscripten_glDrawElements(...args),
    th: (...args) => _emscripten_glDrawElementsInstanced(...args),
    sh: (...args) => _emscripten_glDrawElementsInstancedANGLE(...args),
    rh: (...args) => _emscripten_glDrawElementsInstancedARB(...args),
    qh: (...args) => _emscripten_glDrawElementsInstancedEXT(...args),
    ph: (...args) => _emscripten_glDrawElementsInstancedNV(...args),
    oh: (...args) => _emscripten_glDrawRangeElements(...args),
    nh: (...args) => _emscripten_glEnable(...args),
    mh: (...args) => _emscripten_glEnableVertexAttribArray(...args),
    lh: (...args) => _emscripten_glEndQuery(...args),
    kh: (...args) => _emscripten_glEndQueryEXT(...args),
    jh: (...args) => _emscripten_glEndTransformFeedback(...args),
    ih: (...args) => _emscripten_glFenceSync(...args),
    hh: (...args) => _emscripten_glFinish(...args),
    gh: (...args) => _emscripten_glFlush(...args),
    fh: (...args) => _emscripten_glFlushMappedBufferRange(...args),
    eh: (...args) => _emscripten_glFramebufferRenderbuffer(...args),
    dh: (...args) => _emscripten_glFramebufferTexture2D(...args),
    ch: (...args) => _emscripten_glFramebufferTextureLayer(...args),
    bh: (...args) => _emscripten_glFrontFace(...args),
    ah: (...args) => _emscripten_glGenBuffers(...args),
    $g: (...args) => _emscripten_glGenFramebuffers(...args),
    _g: (...args) => _emscripten_glGenQueries(...args),
    Zg: (...args) => _emscripten_glGenQueriesEXT(...args),
    Yg: (...args) => _emscripten_glGenRenderbuffers(...args),
    Xg: (...args) => _emscripten_glGenSamplers(...args),
    Wg: (...args) => _emscripten_glGenTextures(...args),
    Vg: (...args) => _emscripten_glGenTransformFeedbacks(...args),
    Ug: (...args) => _emscripten_glGenVertexArrays(...args),
    Tg: (...args) => _emscripten_glGenVertexArraysOES(...args),
    Sg: (...args) => _emscripten_glGenerateMipmap(...args),
    Rg: (...args) => _emscripten_glGetActiveAttrib(...args),
    Qg: (...args) => _emscripten_glGetActiveUniform(...args),
    Pg: (...args) => _emscripten_glGetActiveUniformBlockName(...args),
    Og: (...args) => _emscripten_glGetActiveUniformBlockiv(...args),
    Ng: (...args) => _emscripten_glGetActiveUniformsiv(...args),
    Mg: (...args) => _emscripten_glGetAttachedShaders(...args),
    Lg: (...args) => _emscripten_glGetAttribLocation(...args),
    Kg: (...args) => _emscripten_glGetBooleanv(...args),
    Jg: (...args) => _emscripten_glGetBufferParameteri64v(...args),
    Ig: (...args) => _emscripten_glGetBufferParameteriv(...args),
    Hg: (...args) => _emscripten_glGetBufferPointerv(...args),
    Gg: (...args) => _emscripten_glGetError(...args),
    Fg: (...args) => _emscripten_glGetFloatv(...args),
    Eg: (...args) => _emscripten_glGetFragDataLocation(...args),
    Dg: (...args) => _emscripten_glGetFramebufferAttachmentParameteriv(...args),
    Cg: (...args) => _emscripten_glGetInteger64i_v(...args),
    Bg: (...args) => _emscripten_glGetInteger64v(...args),
    Ag: (...args) => _emscripten_glGetIntegeri_v(...args),
    zg: (...args) => _emscripten_glGetIntegerv(...args),
    yg: (...args) => _emscripten_glGetInternalformativ(...args),
    xg: (...args) => _emscripten_glGetProgramBinary(...args),
    wg: (...args) => _emscripten_glGetProgramInfoLog(...args),
    vg: (...args) => _emscripten_glGetProgramiv(...args),
    ug: (...args) => _emscripten_glGetQueryObjecti64vEXT(...args),
    tg: (...args) => _emscripten_glGetQueryObjectivEXT(...args),
    sg: (...args) => _emscripten_glGetQueryObjectui64vEXT(...args),
    rg: (...args) => _emscripten_glGetQueryObjectuiv(...args),
    qg: (...args) => _emscripten_glGetQueryObjectuivEXT(...args),
    pg: (...args) => _emscripten_glGetQueryiv(...args),
    og: (...args) => _emscripten_glGetQueryivEXT(...args),
    ng: (...args) => _emscripten_glGetRenderbufferParameteriv(...args),
    mg: (...args) => _emscripten_glGetSamplerParameterfv(...args),
    lg: (...args) => _emscripten_glGetSamplerParameteriv(...args),
    kg: (...args) => _emscripten_glGetShaderInfoLog(...args),
    jg: (...args) => _emscripten_glGetShaderPrecisionFormat(...args),
    ig: (...args) => _emscripten_glGetShaderSource(...args),
    hg: (...args) => _emscripten_glGetShaderiv(...args),
    gg: (...args) => _emscripten_glGetString(...args),
    fg: (...args) => _emscripten_glGetStringi(...args),
    eg: (...args) => _emscripten_glGetSynciv(...args),
    dg: (...args) => _emscripten_glGetTexParameterfv(...args),
    cg: (...args) => _emscripten_glGetTexParameteriv(...args),
    bg: (...args) => _emscripten_glGetTransformFeedbackVarying(...args),
    ag: (...args) => _emscripten_glGetUniformBlockIndex(...args),
    $f: (...args) => _emscripten_glGetUniformIndices(...args),
    _f: (...args) => _emscripten_glGetUniformLocation(...args),
    Zf: (...args) => _emscripten_glGetUniformfv(...args),
    Yf: (...args) => _emscripten_glGetUniformiv(...args),
    Xf: (...args) => _emscripten_glGetUniformuiv(...args),
    Wf: (...args) => _emscripten_glGetVertexAttribIiv(...args),
    Vf: (...args) => _emscripten_glGetVertexAttribIuiv(...args),
    Uf: (...args) => _emscripten_glGetVertexAttribPointerv(...args),
    Tf: (...args) => _emscripten_glGetVertexAttribfv(...args),
    Sf: (...args) => _emscripten_glGetVertexAttribiv(...args),
    Rf: (...args) => _emscripten_glHint(...args),
    Qf: (...args) => _emscripten_glInvalidateFramebuffer(...args),
    Pf: (...args) => _emscripten_glInvalidateSubFramebuffer(...args),
    Of: (...args) => _emscripten_glIsBuffer(...args),
    Nf: (...args) => _emscripten_glIsEnabled(...args),
    Mf: (...args) => _emscripten_glIsFramebuffer(...args),
    Lf: (...args) => _emscripten_glIsProgram(...args),
    Kf: (...args) => _emscripten_glIsQuery(...args),
    Jf: (...args) => _emscripten_glIsQueryEXT(...args),
    If: (...args) => _emscripten_glIsRenderbuffer(...args),
    Hf: (...args) => _emscripten_glIsSampler(...args),
    Gf: (...args) => _emscripten_glIsShader(...args),
    Ff: (...args) => _emscripten_glIsSync(...args),
    Ef: (...args) => _emscripten_glIsTexture(...args),
    Df: (...args) => _emscripten_glIsTransformFeedback(...args),
    Cf: (...args) => _emscripten_glIsVertexArray(...args),
    Bf: (...args) => _emscripten_glIsVertexArrayOES(...args),
    Af: (...args) => _emscripten_glLineWidth(...args),
    zf: (...args) => _emscripten_glLinkProgram(...args),
    yf: (...args) => _emscripten_glMapBufferRange(...args),
    xf: (...args) => _emscripten_glPauseTransformFeedback(...args),
    wf: (...args) => _emscripten_glPixelStorei(...args),
    vf: (...args) => _emscripten_glPolygonModeWEBGL(...args),
    uf: (...args) => _emscripten_glPolygonOffset(...args),
    tf: (...args) => _emscripten_glPolygonOffsetClampEXT(...args),
    sf: (...args) => _emscripten_glProgramBinary(...args),
    rf: (...args) => _emscripten_glProgramParameteri(...args),
    qf: (...args) => _emscripten_glQueryCounterEXT(...args),
    pf: (...args) => _emscripten_glReadBuffer(...args),
    of: (...args) => _emscripten_glReadPixels(...args),
    nf: (...args) => _emscripten_glReleaseShaderCompiler(...args),
    mf: (...args) => _emscripten_glRenderbufferStorage(...args),
    lf: (...args) => _emscripten_glRenderbufferStorageMultisample(...args),
    kf: (...args) => _emscripten_glResumeTransformFeedback(...args),
    jf: (...args) => _emscripten_glSampleCoverage(...args),
    hf: (...args) => _emscripten_glSamplerParameterf(...args),
    gf: (...args) => _emscripten_glSamplerParameterfv(...args),
    ff: (...args) => _emscripten_glSamplerParameteri(...args),
    ef: (...args) => _emscripten_glSamplerParameteriv(...args),
    df: (...args) => _emscripten_glScissor(...args),
    cf: (...args) => _emscripten_glShaderBinary(...args),
    bf: (...args) => _emscripten_glShaderSource(...args),
    af: (...args) => _emscripten_glStencilFunc(...args),
    $e: (...args) => _emscripten_glStencilFuncSeparate(...args),
    _e: (...args) => _emscripten_glStencilMask(...args),
    Ze: (...args) => _emscripten_glStencilMaskSeparate(...args),
    Ye: (...args) => _emscripten_glStencilOp(...args),
    Xe: (...args) => _emscripten_glStencilOpSeparate(...args),
    We: (...args) => _emscripten_glTexImage2D(...args),
    Ve: (...args) => _emscripten_glTexImage3D(...args),
    Ue: (...args) => _emscripten_glTexParameterf(...args),
    Te: (...args) => _emscripten_glTexParameterfv(...args),
    Se: (...args) => _emscripten_glTexParameteri(...args),
    Re: (...args) => _emscripten_glTexParameteriv(...args),
    Qe: (...args) => _emscripten_glTexStorage2D(...args),
    Pe: (...args) => _emscripten_glTexStorage3D(...args),
    Oe: (...args) => _emscripten_glTexSubImage2D(...args),
    Ne: (...args) => _emscripten_glTexSubImage3D(...args),
    Me: (...args) => _emscripten_glTransformFeedbackVaryings(...args),
    Le: (...args) => _emscripten_glUniform1f(...args),
    Ke: (...args) => _emscripten_glUniform1fv(...args),
    Je: (...args) => _emscripten_glUniform1i(...args),
    Ie: (...args) => _emscripten_glUniform1iv(...args),
    He: (...args) => _emscripten_glUniform1ui(...args),
    Ge: (...args) => _emscripten_glUniform1uiv(...args),
    Fe: (...args) => _emscripten_glUniform2f(...args),
    Ee: (...args) => _emscripten_glUniform2fv(...args),
    De: (...args) => _emscripten_glUniform2i(...args),
    Ce: (...args) => _emscripten_glUniform2iv(...args),
    Be: (...args) => _emscripten_glUniform2ui(...args),
    Ae: (...args) => _emscripten_glUniform2uiv(...args),
    ze: (...args) => _emscripten_glUniform3f(...args),
    ye: (...args) => _emscripten_glUniform3fv(...args),
    xe: (...args) => _emscripten_glUniform3i(...args),
    we: (...args) => _emscripten_glUniform3iv(...args),
    ve: (...args) => _emscripten_glUniform3ui(...args),
    ue: (...args) => _emscripten_glUniform3uiv(...args),
    te: (...args) => _emscripten_glUniform4f(...args),
    se: (...args) => _emscripten_glUniform4fv(...args),
    re: (...args) => _emscripten_glUniform4i(...args),
    qe: (...args) => _emscripten_glUniform4iv(...args),
    pe: (...args) => _emscripten_glUniform4ui(...args),
    oe: (...args) => _emscripten_glUniform4uiv(...args),
    ne: (...args) => _emscripten_glUniformBlockBinding(...args),
    me: (...args) => _emscripten_glUniformMatrix2fv(...args),
    le: (...args) => _emscripten_glUniformMatrix2x3fv(...args),
    ke: (...args) => _emscripten_glUniformMatrix2x4fv(...args),
    je: (...args) => _emscripten_glUniformMatrix3fv(...args),
    ie: (...args) => _emscripten_glUniformMatrix3x2fv(...args),
    he: (...args) => _emscripten_glUniformMatrix3x4fv(...args),
    ge: (...args) => _emscripten_glUniformMatrix4fv(...args),
    fe: (...args) => _emscripten_glUniformMatrix4x2fv(...args),
    ee: (...args) => _emscripten_glUniformMatrix4x3fv(...args),
    de: (...args) => _emscripten_glUnmapBuffer(...args),
    ce: (...args) => _emscripten_glUseProgram(...args),
    be: (...args) => _emscripten_glValidateProgram(...args),
    ae: (...args) => _emscripten_glVertexAttrib1f(...args),
    $d: (...args) => _emscripten_glVertexAttrib1fv(...args),
    _d: (...args) => _emscripten_glVertexAttrib2f(...args),
    Zd: (...args) => _emscripten_glVertexAttrib2fv(...args),
    Yd: (...args) => _emscripten_glVertexAttrib3f(...args),
    Xd: (...args) => _emscripten_glVertexAttrib3fv(...args),
    Wd: (...args) => _emscripten_glVertexAttrib4f(...args),
    Vd: (...args) => _emscripten_glVertexAttrib4fv(...args),
    Ud: (...args) => _emscripten_glVertexAttribDivisor(...args),
    Td: (...args) => _emscripten_glVertexAttribDivisorANGLE(...args),
    Sd: (...args) => _emscripten_glVertexAttribDivisorARB(...args),
    Rd: (...args) => _emscripten_glVertexAttribDivisorEXT(...args),
    Qd: (...args) => _emscripten_glVertexAttribDivisorNV(...args),
    Pd: (...args) => _emscripten_glVertexAttribI4i(...args),
    Od: (...args) => _emscripten_glVertexAttribI4iv(...args),
    Nd: (...args) => _emscripten_glVertexAttribI4ui(...args),
    Md: (...args) => _emscripten_glVertexAttribI4uiv(...args),
    Ld: (...args) => _emscripten_glVertexAttribIPointer(...args),
    Kd: (...args) => _emscripten_glVertexAttribPointer(...args),
    Jd: (...args) => _emscripten_glViewport(...args),
    Id: (...args) => _emscripten_glWaitSync(...args),
    Ba: (...args) => _emscripten_has_asyncify(...args),
    Hd: (...args) => _emscripten_is_main_browser_thread(...args),
    Gd: (...args) => _emscripten_request_fullscreen_strategy(...args),
    Ib: (...args) => _emscripten_request_pointerlock(...args),
    Fd: (...args) => _emscripten_resize_heap(...args),
    Ed: (...args) => _emscripten_run_script_int(...args),
    Hb: (...args) => _emscripten_sample_gamepad_data(...args),
    Gb: (...args) => _emscripten_set_beforeunload_callback_on_thread(...args),
    Fb: (...args) => _emscripten_set_blur_callback_on_thread(...args),
    da: (...args) => _emscripten_set_canvas_element_size(...args),
    Aa: (...args) => _emscripten_set_element_css_size(...args),
    Eb: (...args) => _emscripten_set_focus_callback_on_thread(...args),
    Db: (...args) => _emscripten_set_fullscreenchange_callback_on_thread(...args),
    Cb: (...args) => _emscripten_set_gamepadconnected_callback_on_thread(...args),
    Bb: (...args) => _emscripten_set_gamepaddisconnected_callback_on_thread(...args),
    Ab: (...args) => _emscripten_set_keydown_callback_on_thread(...args),
    zb: (...args) => _emscripten_set_keypress_callback_on_thread(...args),
    yb: (...args) => _emscripten_set_keyup_callback_on_thread(...args),
    Dd: (...args) => _emscripten_set_main_loop(...args),
    xb: (...args) => _emscripten_set_mousedown_callback_on_thread(...args),
    wb: (...args) => _emscripten_set_mouseenter_callback_on_thread(...args),
    vb: (...args) => _emscripten_set_mouseleave_callback_on_thread(...args),
    ub: (...args) => _emscripten_set_mousemove_callback_on_thread(...args),
    tb: (...args) => _emscripten_set_mouseup_callback_on_thread(...args),
    sb: (...args) => _emscripten_set_pointerlockchange_callback_on_thread(...args),
    rb: (...args) => _emscripten_set_resize_callback_on_thread(...args),
    qb: (...args) => _emscripten_set_touchcancel_callback_on_thread(...args),
    pb: (...args) => _emscripten_set_touchend_callback_on_thread(...args),
    ob: (...args) => _emscripten_set_touchmove_callback_on_thread(...args),
    nb: (...args) => _emscripten_set_touchstart_callback_on_thread(...args),
    mb: (...args) => _emscripten_set_visibilitychange_callback_on_thread(...args),
    lb: (...args) => _emscripten_set_wheel_callback_on_thread(...args),
    Cd: (...args) => _emscripten_set_window_title(...args),
    za: (...args) => _emscripten_sleep(...args),
    Bd: (...args) => _emscripten_start_fetch(...args),
    ik: (...args) => _environ_get(...args),
    hk: (...args) => _environ_sizes_get(...args),
    Ad: (...args) => _exit(...args),
    ja: (...args) => _fd_close(...args),
    dc: (...args) => _fd_read(...args),
    gk: (...args) => _fd_seek(...args),
    cc: (...args) => _fd_write(...args),
    zd: (...args) => _glActiveTexture(...args),
    kb: (...args) => _glAttachShader(...args),
    _: (...args) => _glBindBuffer(...args),
    yd: (...args) => _glBindBufferBase(...args),
    Z: (...args) => _glBindFramebuffer(...args),
    jb: (...args) => _glBindRenderbuffer(...args),
    xd: (...args) => _glBindSampler(...args),
    M: (...args) => _glBindTexture(...args),
    wd: (...args) => _glBindVertexArray(...args),
    vd: (...args) => _glBlendEquationSeparate(...args),
    ud: (...args) => _glBlendFuncSeparate(...args),
    Y: (...args) => _glBufferData(...args),
    td: (...args) => _glClear(...args),
    sd: (...args) => _glClearColor(...args),
    rd: (...args) => _glClearDepthf(...args),
    qd: (...args) => _glClearStencil(...args),
    pd: (...args) => _glColorMask(...args),
    od: (...args) => _glCompileShader(...args),
    nd: (...args) => _glCopyTexSubImage2D(...args),
    md: (...args) => _glCreateProgram(...args),
    ld: (...args) => _glCreateShader(...args),
    kd: (...args) => _glCullFace(...args),
    ya: (...args) => _glDeleteBuffers(...args),
    ib: (...args) => _glDeleteFramebuffers(...args),
    jd: (...args) => _glDeleteProgram(...args),
    id: (...args) => _glDeleteRenderbuffers(...args),
    hd: (...args) => _glDeleteSamplers(...args),
    hb: (...args) => _glDeleteShader(...args),
    gd: (...args) => _glDeleteTextures(...args),
    fd: (...args) => _glDeleteVertexArrays(...args),
    ed: (...args) => _glDepthFunc(...args),
    xa: (...args) => _glDepthMask(...args),
    dd: (...args) => _glDepthRangef(...args),
    Q: (...args) => _glDisable(...args),
    cd: (...args) => _glDisableVertexAttribArray(...args),
    bd: (...args) => _glDrawArraysInstanced(...args),
    ad: (...args) => _glDrawBuffers(...args),
    $c: (...args) => _glDrawElementsInstanced(...args),
    P: (...args) => _glEnable(...args),
    _c: (...args) => _glEnableVertexAttribArray(...args),
    Zc: (...args) => _glFramebufferRenderbuffer(...args),
    gb: (...args) => _glFramebufferTexture2D(...args),
    Yc: (...args) => _glFrontFace(...args),
    wa: (...args) => _glGenBuffers(...args),
    fb: (...args) => _glGenFramebuffers(...args),
    Xc: (...args) => _glGenRenderbuffers(...args),
    Wc: (...args) => _glGenSamplers(...args),
    Vc: (...args) => _glGenTextures(...args),
    Uc: (...args) => _glGenVertexArrays(...args),
    Tc: (...args) => _glGenerateMipmap(...args),
    C: (...args) => _glGetIntegerv(...args),
    Sc: (...args) => _glGetProgramInfoLog(...args),
    eb: (...args) => _glGetProgramiv(...args),
    Rc: (...args) => _glGetShaderInfoLog(...args),
    db: (...args) => _glGetShaderiv(...args),
    Qc: (...args) => _glGetStringi(...args),
    Pc: (...args) => _glGetUniformBlockIndex(...args),
    Oc: (...args) => _glGetUniformLocation(...args),
    Nc: (...args) => _glLinkProgram(...args),
    cb: (...args) => _glPixelStorei(...args),
    Mc: (...args) => _glPolygonOffset(...args),
    Lc: (...args) => _glReadPixels(...args),
    Kc: (...args) => _glRenderbufferStorage(...args),
    Jc: (...args) => _glSamplerParameterf(...args),
    pa: (...args) => _glSamplerParameteri(...args),
    bb: (...args) => _glScissor(...args),
    Ic: (...args) => _glShaderSource(...args),
    Gc: (...args) => _glStencilMask(...args),
    Fc: (...args) => _glStencilOp(...args),
    Ec: (...args) => _glTexImage2D(...args),
    Dc: (...args) => _glTexParameteri(...args),
    Cc: (...args) => _glTexSubImage2D(...args),
    Bc: (...args) => _glUniform1i(...args),
    Ac: (...args) => _glUniformBlockBinding(...args),
    va: (...args) => _glUseProgram(...args),
    zc: (...args) => _glVertexAttribDivisor(...args),
    yc: (...args) => _glVertexAttribPointer(...args),
    xc: (...args) => _glViewport(...args),
    ab: invoke_diii,
    wc: invoke_f,
    ca: invoke_fff,
    $a: invoke_ffffi,
    ba: invoke_fi,
    F: invoke_fii,
    oa: invoke_fiif,
    na: invoke_fiii,
    _a: invoke_fiiif,
    t: invoke_i,
    Za: invoke_idiiii,
    d: invoke_ii,
    Ya: invoke_iif,
    aa: invoke_iifiiiiiii,
    k: invoke_iii,
    w: invoke_iiifffii,
    A: invoke_iiiffii,
    ua: invoke_iiifi,
    j: invoke_iiii,
    ta: invoke_iiiid,
    Xa: invoke_iiiif,
    Wa: invoke_iiiifi,
    Va: invoke_iiiifii,
    m: invoke_iiiii,
    vc: invoke_iiiiiff,
    X: invoke_iiiiifffffff,
    T: invoke_iiiiifiiii,
    L: invoke_iiiiifiiiii,
    o: invoke_iiiiii,
    r: invoke_iiiiiii,
    K: invoke_iiiiiiii,
    Ua: invoke_iiiiiiiii,
    ma: invoke_iiiiiiiiiiii,
    Ta: invoke_iiiiiiiiiiiii,
    W: invoke_iiji,
    la: invoke_iijiii,
    uc: invoke_iijji,
    Sa: invoke_iijjiii,
    tc: invoke_ijjiiii,
    O: invoke_j,
    Ra: invoke_ji,
    Qa: invoke_jiiii,
    g: invoke_v,
    Pa: invoke_vdii,
    sc: invoke_vf,
    e: invoke_vi,
    N: invoke_vif,
    Oa: invoke_viff,
    rc: invoke_vifffii,
    J: invoke_vifi,
    b: invoke_vii,
    I: invoke_viif,
    qc: invoke_viiff,
    Na: invoke_viifi,
    i: invoke_viii,
    Ma: invoke_viiif,
    pc: invoke_viiiffi,
    sa: invoke_viiifi,
    x: invoke_viiifiiiiifi,
    l: invoke_viiii,
    La: invoke_viiiiffffiiif,
    Ka: invoke_viiiifi,
    oc: invoke_viiiifif,
    p: invoke_viiiii,
    s: invoke_viiiiii,
    E: invoke_viiiiiii,
    S: invoke_viiiiiiii,
    nc: invoke_viiiiiiiii,
    V: invoke_viiiiiiiiii,
    mc: invoke_viiiiiiiiiii,
    ka: invoke_viiiiiiiiiiiiiii,
    lc: invoke_viij,
    Ja: invoke_viijii,
    kc: invoke_vij,
    jc: invoke_viji,
    ic: invoke_vjjii,
    hc: _llvm_eh_typeid_for
    
};
